
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ABID
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public Add() {
        initComponents();
        this.setVisible(true);
//        setVisibleAdd(false);
//        setVisibleAddClasses(false);
    }

//    public void setVisibleAdd(boolean x)
//    {
//        addClassesButton.setVisible(x);
//        taskButton.setVisible(x);
////        setVisibleAddClasses(x);
//    }
    
//    public void setVisibleAddClasses(boolean x)
//    {
//        classNameLabel.setVisible(x);
//        classNameTextField.setVisible(x);
//        classStartDateLabel.setVisible(x);
//        classStartDateTextField.setVisible(x);
//        classEndDateLabel.setVisible(x);
//        classEndDateTextField.setVisible(x);
//    }
    
    private void initComponents1()
    {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        base.setSize(764,467);
        menu = new javax.swing.JLabel();
        tasks = new javax.swing.JButton();
        classesButton = new javax.swing.JButton();
        calendar = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        addClassButton = new javax.swing.JButton();
        addTaskButton = new javax.swing.JButton();
        exit2 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);

        base.setBackground(new java.awt.Color(51, 51, 51));
        base.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                baseMouseDragged(evt);
            }
        });
        base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                baseMouseReleased(evt);
            }
        });

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        tasks.setBackground(new java.awt.Color(0, 0, 0));
        tasks.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        tasks.setForeground(new java.awt.Color(255, 255, 255));
        tasks.setText("tasks");
        tasks.setBorderPainted(false);
        tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasksMouseClicked(evt);
            }
        });
        tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksActionPerformed(evt);
            }
        });

        classesButton.setBackground(new java.awt.Color(0, 0, 0));
        classesButton.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        classesButton.setForeground(new java.awt.Color(255, 255, 255));
        classesButton.setText("Classes");
        classesButton.setBorderPainted(false);
        classesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesButtonMouseClicked(evt);
            }
        });
        classesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesButtonActionPerformed(evt);
            }
        });

        calendar.setBackground(new java.awt.Color(0, 0, 0));
        calendar.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        calendar.setForeground(new java.awt.Color(255, 255, 255));
        calendar.setText("Calender");
        calendar.setBorderPainted(false);
        calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarMouseClicked(evt);
            }
        });
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setBorderPainted(false);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        content.setBackground(new java.awt.Color(0, 0, 0));

        addClassButton.setText("Class");
        addClassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClassButtonMouseClicked(evt);
            }
        });

        addTaskButton.setText("Task");
        addTaskButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTaskButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(addClassButton)
                .addGap(83, 83, 83)
                .addComponent(addTaskButton)
                .addGap(160, 160, 160))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClassButton)
                    .addComponent(addTaskButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exit2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mueez\\Downloads\\version 12-10\\StudyLifeLOL\\src\\main\\java\\icons\\icons8_shutdown_32.png"));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        menu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mueez\\Downloads\\version 12-10\\StudyLifeLOL\\src\\main\\java\\icons\\icons8_menu_32.png"));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tasks, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(classesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(65, 65, 65))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menu)
                                .addGroup(baseLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(user))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menu2)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit2)
                        .addContainerGap())))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tasks, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit2)
                        .addContainerGap())))
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classesButtonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarActionPerformed

    private void tasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tasksActionPerformed
    int xx,xy;
    public boolean isMenuClickedOnce=false;
    private void baseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMousePressed
        // TODO add your handling code here:
        setOpacity((float) .8);
        xx=evt.getX();
        
        xy=evt.getY();
    }//GEN-LAST:event_baseMousePressed

    private void baseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1);
    }//GEN-LAST:event_baseMouseReleased

    private void baseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_baseMouseDragged
    int xlength=630;
    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
       // content.setSize(764,467);
        
       if(!this.isMenuClickedOnce)
       {
         // System.out.println("once");
        Thread sliding=new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    int i=0;
                    for( i=xlength;i<=764;i++)
                    {
                        Thread.sleep(1);
                        content.setSize(i,467);
                    }
                    xlength=i-1;
                   // System.out.print(xlength);
                    
                   
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
                
            }
           
                   
       };sliding.start();
       this.isMenuClickedOnce=true;
       }
       
       else
       {
        Thread unsliding=new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    int i=0;
                    for( i=xlength;i>=630;i--)
                    {
                        Thread.sleep(1);
                        content.setSize(i,467);
                    }
                    xlength=i+1;
                    System.out.println(xlength);
                    
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
            }
           
        
       };unsliding.start();
       
       this.isMenuClickedOnce=false;
       
       
       }
       
      // this.isMenuClickedOnce=(this.isMenuClickedOnce==true)? false :true;
       
    }//GEN-LAST:event_menuMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        
//        setVisibleAdd(true);
    }//GEN-LAST:event_AddMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void calendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseClicked
        JFrameMain mainFrame = new JFrameMain();
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //mainFrame.setSize(670, 500);
        //mainFrame.getContentPane().setBackground( new Color (102, 102, 102));
        //mainFrame.setLocationRelativeTo(null);
//        dispose();
        mainFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_calendarMouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        dispose();
    }//GEN-LAST:event_exit2MouseClicked

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        menuMouseClicked(evt);
    }//GEN-LAST:event_menu2MouseClicked

    private void addClassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClassButtonMouseClicked
        AddClass addClassFrame = new AddClass();
        addClassFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        addClassFrame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_addClassButtonMouseClicked

    private void addTaskButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTaskButtonMouseClicked
        AddTask addTaskFrame = new AddTask();
        addTaskFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        addTaskFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_addTaskButtonMouseClicked

    private void tasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasksMouseClicked
        TaskFrame taskFrame = new TaskFrame();
        taskFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        taskFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_tasksMouseClicked

    private void classesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseClicked
        ClassFrame classFrame = new ClassFrame();
        classFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        classFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_classesButtonMouseClicked

    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainWindow().setVisible(true);
                
               // MainWindow().content.setSize(764,467);
//               try{
//                   if(con != null)
//                       con.close();
//               }catch(Exception e)
//               {
//                   System.out.println("oh no: " + e);
//               }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton addClassButton;
    private javax.swing.JButton addTaskButton;
    private javax.swing.JPanel base;
    private javax.swing.JButton calendar;
    private javax.swing.JButton classesButton;
    private javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu2;
    private javax.swing.JButton tasks;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
