
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.*;
import java.time.YearMonth;
import java.util.Calendar;
import java.util.Date;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ABID
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    private JButton jButtonIn1;
    private JLabel jlb;
    private Calendar c;
    private DatabaseClass dbObject;
    private ResultSet rs;
    
    public JFrameMain() {
        
        initComponents();
        //content.add(jPanel1);
//        jPanel1.setSize(764,467);
       // jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        this.setVisible(true);
        dbObject = new DatabaseClass();
//        setVisibleAdd(false);
//        setVisibleAddClasses(false);
        c = Calendar.getInstance();
        System.out.println(c);
         display(c);
    }

    public void setVisibleAdd(boolean x)
    {
//        addClassesButton.setVisible(x);
//        taskButton.setVisible(x);
    }
    
    public void setVisibleAddClasses(boolean x)
    {
//        classNameLabel.setVisible(x);
//        classNameTextField.setVisible(x);
//        classStartDateLabel.setVisible(x);
//        classStartDateTextField.setVisible(x);
//        classEndDateLabel.setVisible(x);
//        classEndDateTextField.setVisible(x);
    }
    
    private void initComponents1()
    {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        tasks = new javax.swing.JButton();
        classesButton = new javax.swing.JButton();
        calendar = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        upperPart = new javax.swing.JPanel();
        month = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        forwordButton = new javax.swing.JButton();
        timeDate = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);

        base.setBackground(new java.awt.Color(51, 51, 51));
        base.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                baseMouseDragged(evt);
            }
        });
        base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                baseMouseReleased(evt);
            }
        });

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        tasks.setBackground(new java.awt.Color(0, 0, 0));
        tasks.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        tasks.setForeground(new java.awt.Color(255, 255, 255));
        tasks.setText("tasks");
        tasks.setBorderPainted(false);
        tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasksMouseClicked(evt);
            }
        });
        tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksActionPerformed(evt);
            }
        });

        classesButton.setBackground(new java.awt.Color(0, 0, 0));
        classesButton.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        classesButton.setForeground(new java.awt.Color(255, 255, 255));
        classesButton.setText("Classes");
        classesButton.setBorderPainted(false);
        classesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesButtonMouseClicked(evt);
            }
        });
        classesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesButtonActionPerformed(evt);
            }
        });

        calendar.setBackground(new java.awt.Color(0, 0, 0));
        calendar.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        calendar.setForeground(new java.awt.Color(255, 255, 255));
        calendar.setText("Calender");
        calendar.setBorderPainted(false);
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setBorderPainted(false);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        content.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        upperPart.setBackground(new java.awt.Color(0, 0, 0));
        upperPart.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        month.setBackground(new java.awt.Color(0, 0, 0));
        month.setFont(new java.awt.Font("Showcard Gothic", 0, 15)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setText("                         example");
        month.setToolTipText("");

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorderPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        forwordButton.setBackground(new java.awt.Color(255, 255, 255));
        forwordButton.setText("Forward");
        forwordButton.setBorderPainted(false);
        forwordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwordButtonActionPerformed(evt);
            }
        });

        timeDate.setBackground(new java.awt.Color(0, 0, 0));
        timeDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeDate.setForeground(new java.awt.Color(255, 255, 255));
        timeDate.setText("jLabel3");

        javax.swing.GroupLayout upperPartLayout = new javax.swing.GroupLayout(upperPart);
        upperPart.setLayout(upperPartLayout);
        upperPartLayout.setHorizontalGroup(
            upperPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPartLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(upperPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(month, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(timeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(forwordButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upperPartLayout.setVerticalGroup(
            upperPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperPartLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(upperPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forwordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(upperPartLayout.createSequentialGroup()
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeDate, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(upperPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mueez\\Downloads\\version 12-10\\StudyLifeLOL\\src\\main\\java\\icons\\icons8_menu_32.png"));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        exit2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mueez\\Downloads\\version 12-10\\StudyLifeLOL\\src\\main\\java\\icons\\icons8_shutdown_32.png"));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tasks, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(classesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menu)
                                    .addGroup(baseLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(user)
                                            .addComponent(jLabel1))))
                                .addContainerGap()))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                            .addComponent(exit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(exit2)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(menu2)
                        .addContainerGap())))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tasks, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit2)
                        .addContainerGap())))
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classesButtonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarActionPerformed

    private void tasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tasksActionPerformed
    int xx,xy;
    public boolean isMenuClickedOnce=false;
    private void baseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMousePressed
        // TODO add your handling code here:
        setOpacity((float) .8);
        xx=evt.getX();
        
        xy=evt.getY();
    }//GEN-LAST:event_baseMousePressed

    private void baseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1);
    }//GEN-LAST:event_baseMouseReleased

    private void baseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_baseMouseDragged
    int xlength=630;
    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
       // content.setSize(764,467);
        
       if(!this.isMenuClickedOnce)
       {
          System.out.println("once");
        Thread sliding=new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    int i=0;
                    for( i=xlength;i<=764;i++)
                    {
//                        Thread.sleep(1);
                        content.setSize(i,467);
                    }
                    xlength=i-1;
                    System.out.print(xlength);
                    
                   
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
                
            }
           
                   
       };sliding.start();
       this.isMenuClickedOnce=true;
       }
       
       else
       {
        Thread unsliding=new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    int i=0;
                    for( i=xlength;i>=630;i--)
                    {
//                        Thread.sleep(1);
                        content.setSize(i,467);
                    }
                    xlength=i+1;
                    System.out.println(xlength);
                    
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
            }
           
        
       };unsliding.start();
       
       this.isMenuClickedOnce=false;
       
       
       }
       
      // this.isMenuClickedOnce=(this.isMenuClickedOnce==true)? false :true;
       
    }//GEN-LAST:event_menuMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        
//        setVisibleAdd(true);
          Add adFrame = new Add();
          adFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
          adFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void forwordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forwordButtonActionPerformed

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        menuMouseClicked(evt);
    }//GEN-LAST:event_menu2MouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        dispose();
    }//GEN-LAST:event_exit2MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void tasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasksMouseClicked
        TaskFrame taskFrame = new TaskFrame();
        taskFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        taskFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_tasksMouseClicked

    private void classesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseClicked
        ClassFrame classFrame = new ClassFrame();
        classFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        classFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_classesButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        int year = c.get(Calendar.YEAR);
        int month = c.get(Calendar.MONTH);
        if(month==0)
        {
            month=11;
            year--;
        }
        else month--;
        
        int day =1;
        c.set(year, month, day);
        System.out.println(year+"  "+month +" " + day);
        reset();
        display(c);
    }//GEN-LAST:event_backButtonMouseClicked

    public JFrameMain(Calendar t) {
        initComponents();
         
         jPanel1.setSize(764,467);
         jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        this.setVisible(true);
        display(t);
    }
    public void display(Calendar c)
    {
        String months[]={"Januray","February","March","April","May",
            "June","July","August","September","October","November","December"};
        int monthName=c.get(Calendar.MONTH);
        
        Thread showTime=new Thread()
        {
            @Override
            public void run()
            {
                while(true)
                {
                  String time= new java.text.SimpleDateFormat("yyyy.MM.dd HH:mm:ss").format(new Date());
                  timeDate.setText("         "+time);
                }
            }
            
            
        };showTime.start();
        
        month.setText("                   "+months[monthName]);
        month.setPreferredSize(new Dimension(100,10));
        month.setForeground(Color.white);
        int todaysDate = c.get(Calendar.DAY_OF_MONTH);
        int daysInMonth = c.getActualMaximum(Calendar.DAY_OF_MONTH);
        c.set(Calendar.DAY_OF_MONTH, 1);
        int day = c.get(Calendar.DAY_OF_WEEK);
        c.set(Calendar.DAY_OF_MONTH, todaysDate);
//         System.out.println(todaysDate);
//        System.out.println(daysInMonth);
//        System.out.println(day);
        
        String[] a = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT" };
        
        jPanel1.setLayout(new GridLayout(0, 7, 0,0));
        
       
     
        for(int i =0; i<7; i++)
        {
            jlb = new JLabel();
            //jlb.setBackground(new Color(78,100,66));
           // jlb.setPreferredSize(new Dimension(10,10));
            jlb.setText("         "+a[i]);
            
            jlb.setBackground(Color.black);
            
          //  jlb.setForeground(new Color(255, 255, 255));
            jlb.setPreferredSize(new Dimension(100, 10));
            jPanel1.add(jlb);
        }
        
        for(int i=0; i<(day-1); i++)
        {
           jButtonIn1 = new JButton();
           
            jButtonIn1.setBackground(new Color(0,0,0));
            jButtonIn1.setForeground(new Color(255, 255, 255));
            jButtonIn1.setVisible(false);
           jPanel1.add(jButtonIn1);
           // jPanel1.setBackground(new java.awt.Color(255,255,255));
        }
        
        for(int i=1; i<=daysInMonth; i++)
        {
//            System.out.println(i);
           final int temp = i;
           jButtonIn1 = new JButton(String.valueOf(i));
           
           if(dbObject.hasTask(makeStringDate(c, temp)))
           {
//               Border border = new Border();
               jButtonIn1.setBorder(new LineBorder(new Color(255, 102, 51), 2));;
           }
           if(i==todaysDate)
           {
               //jButtonIn1.setBorder(BorderFactory.createLineBorder(Color.blue, 2));
               jButtonIn1.setBackground(new Color(92, 140, 68));
              //  jPanel1.setBackground(new java.awt.Color(255,255,255));
           }
           else
           {
               jButtonIn1.setBackground(new Color(99,99,99));
               // jPanel1.setBackground(new java.awt.Color(255,255,255));
           }
           // jButtonIn1.setForeground(new Color(, 0, 0));
           jButtonIn1.addActionListener(
                new ActionListener()
                {
                       public void actionPerformed(ActionEvent event)
                       {
//                           System.out.println(temp);
                           String date = makeStringDate(c, temp);
//                           System.out.println(date);
//                           JOptionPane.showMessageDialog(null, event.getActionCommand());
                           NewJFrame nf = new NewJFrame(date);
                           nf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                           nf.setLocationRelativeTo(null);
                           nf.setVisible(true);
                       }
                }
           );
//            System.out.println("afsd");
         jPanel1.add(jButtonIn1);
          jPanel1.setBackground(new java.awt.Color(255,255,255));
        // jPanel1.setBackground(Color.black);
            
         //jLabel2 = new JLabel(String.valueOf(c));
//         String temp = " ";
//         temp = String.valueOf(todaysDate) + " / " + String.valueOf(c.get(Calendar.MONTH)+1) + " / " +c.get(Calendar.YEAR) ;
         //jLabel2.setText(temp);
            //System.out.println("todays date: " + temp);
         //content.add(jPanel1);
    }
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
         jPanel1.setBackground(new java.awt.Color(255,255,255));
        content.add(jPanel1);
    }
    
    
    public void reset()
    {
        jPanel1 = new JPanel();
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String date = JOptionPane.showInputDialog("Enter date");
        String month = JOptionPane.showInputDialog("Enter month");
        String year = JOptionPane.showInputDialog("Enter year");
        Calendar t = Calendar.getInstance();
        t.set(Integer.parseInt(year), Integer.parseInt(month)-1, Integer.parseInt(date));
        JFrameMain mainFrame = new JFrameMain(t);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainFrame.setLocationRelativeTo(null);
        mainFrame.setVisible(true);
        dispose();
    }
    
    private String makeStringDate(Calendar c, int i)
    {
        int date = i;
        int month = c.get(Calendar.MONTH);
        int year = c.get(Calendar.YEAR);
        month++;
//        System.out.println("yeehaaw: " + date + " " + month + " " + year);
        String todaysDate = "";
        todaysDate = String.valueOf(year) + "-" + String.valueOf(month) + "-" + String.valueOf(date);
        return todaysDate;
    }
    
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
                
               // MainWindow().content.setSize(764,467);
            }
        });
    }

    
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel base;
    private javax.swing.JButton calendar;
    private javax.swing.JButton classesButton;
    private javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit2;
    private javax.swing.JButton forwordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel month;
    private javax.swing.JButton tasks;
    private javax.swing.JLabel timeDate;
    private javax.swing.JPanel upperPart;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
