
import java.awt.*;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.*;
import javax.swing.BoxLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ABID
 */
public class TaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    private DatabaseClass dbObject;
    private ResultSet rsClass;
    private JCheckBox cb = new JCheckBox();
    private JLabel jlab = new JLabel();
    
    public TaskFrame() {
        initComponents();
        this.setVisible(true);
        dbObject = new DatabaseClass();
        setCheckBox();
        
//        HandlerClass handler = new HandlerClass();
//        cb.addItemListener(handler);
        
//        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
//        jPanel1.setBackground(java.awt.Color.WHITE);
//        for(int i=0; i<100; i++)
//        {
//            cb= new JCheckBox();
//        
//        cb.setText("dfsdsfsdf");
//        cb.setForeground(Color.BLACK);
//        cb.setVisible(true);
////        cb.setBackground(Color.BLACK);
//        jPanel1.add(cb);
//        jPanel1.add(Box.createVerticalGlue());
//        jPanel1.add(Box.createVerticalStrut(10));
//        }
//        jPanel1.setVisible(true);
        
        
    }

//    private class HandlerClass implements ItemListener{
//        public void itemStateChanged(ItemEvent event)
//        {
//            if(cb.isSelected())
//            {
//                System.out.println("aaaaaaaaaaaammmmmmmmmmmmm");
//            }
//        }
//    }
    
//    public void setVisibleAdd(boolean x)
//    {
//        addClassesButton.setVisible(x);
//        taskButton.setVisible(x);
////        setVisibleAddClasses(x);
//    }
    
//    public void setVisibleAddClasses(boolean x)
//    {
//        classNameLabel.setVisible(x);
//        classNameTextField.setVisible(x);
//        classStartDateLabel.setVisible(x);
//        classStartDateTextField.setVisible(x);
//        classEndDateLabel.setVisible(x);
//        classEndDateTextField.setVisible(x);
//    }
    
    private void initComponents1()
    {
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                cbActionPerformed(evt);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        base.setSize(764,467);
        menu = new javax.swing.JLabel();
        tasks = new javax.swing.JButton();
        classesButton = new javax.swing.JButton();
        calendar = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        exit2 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setUndecorated(true);

        base.setBackground(new java.awt.Color(51, 51, 51));
        base.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                baseMouseDragged(evt);
            }
        });
        base.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                baseMouseReleased(evt);
            }
        });

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        tasks.setBackground(new java.awt.Color(0, 0, 0));
        tasks.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        tasks.setForeground(new java.awt.Color(255, 255, 255));
        tasks.setText("tasks");
        tasks.setBorderPainted(false);
        tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksActionPerformed(evt);
            }
        });

        classesButton.setBackground(new java.awt.Color(0, 0, 0));
        classesButton.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        classesButton.setForeground(new java.awt.Color(255, 255, 255));
        classesButton.setText("Classes");
        classesButton.setBorderPainted(false);
        classesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesButtonMouseClicked(evt);
            }
        });
        classesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesButtonActionPerformed(evt);
            }
        });

        calendar.setBackground(new java.awt.Color(0, 0, 0));
        calendar.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        calendar.setForeground(new java.awt.Color(255, 255, 255));
        calendar.setText("Calender");
        calendar.setBorderPainted(false);
        calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarMouseClicked(evt);
            }
        });
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setBorderPainted(false);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        content.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(jPanel1);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exit2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mueez\\Downloads\\version 12-10\\StudyLifeLOL\\src\\main\\java\\icons\\icons8_shutdown_32.png"));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        menu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mueez\\Downloads\\version 12-10\\StudyLifeLOL\\src\\main\\java\\icons\\icons8_menu_32.png"));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(menu)
                                .addGroup(baseLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(user))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menu2)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tasks, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(classesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(65, 65, 65)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit2)
                        .addContainerGap())))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tasks, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit2)
                        .addContainerGap())))
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classesButtonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarActionPerformed

    private void tasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tasksActionPerformed
    int xx,xy;
    public boolean isMenuClickedOnce=false;
    private void baseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMousePressed
        // TODO add your handling code here:
        setOpacity((float) .8);
        xx=evt.getX();
        
        xy=evt.getY();
    }//GEN-LAST:event_baseMousePressed

    private void baseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1);
    }//GEN-LAST:event_baseMouseReleased

    private void baseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_baseMouseDragged
    int xlength=630;
    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
       // content.setSize(764,467);
        
       if(!this.isMenuClickedOnce)
       {
         // System.out.println("once");
        Thread sliding=new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    int i=0;
                    for( i=xlength;i<=764;i++)
                    {
                        Thread.sleep(1);
                        content.setSize(i,467);
                    }
                    xlength=i-1;
                   // System.out.print(xlength);
                    
                   
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
                
            }
           
                   
       };sliding.start();
       this.isMenuClickedOnce=true;
       }
       
       else
       {
        Thread unsliding=new Thread()
        {
            @Override
            public void run()
            {
                try
                {
                    int i=0;
                    for( i=xlength;i>=630;i--)
                    {
                        Thread.sleep(1);
                        content.setSize(i,467);
                    }
                    xlength=i+1;
                    System.out.println(xlength);
                    
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
            }
           
        
       };unsliding.start();
       
       this.isMenuClickedOnce=false;
       
       
       }
       
      // this.isMenuClickedOnce=(this.isMenuClickedOnce==true)? false :true;
       
    }//GEN-LAST:event_menuMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        
//        setVisibleAdd(true);
        Add adFrame = new Add();
        adFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        adFrame.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_AddMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void calendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseClicked
        JFrameMain mainFrame = new JFrameMain();
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //mainFrame.setSize(670, 500);
        //mainFrame.getContentPane().setBackground( new Color (102, 102, 102));
        //mainFrame.setLocationRelativeTo(null);
//        dispose();
        mainFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_calendarMouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        dispose();
    }//GEN-LAST:event_exit2MouseClicked

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        menuMouseClicked(evt);
    }//GEN-LAST:event_menu2MouseClicked

    private void classesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesButtonMouseClicked
        ClassFrame classFrame = new ClassFrame();
        classFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        classFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_classesButtonMouseClicked

//    private void cbActionPerformed(java.awt.event.ActionEvent evt)
//    {
//        System.out.println("aaaaaaaaaaaa");
//    }
    
    public void setCheckBox()
    {
        reset();
        Calendar cal = Calendar.getInstance();
        int date = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        month++;
//        System.out.println("yeehaaw: " + date + " " + month + " " + year);
        String todaysDate = "";
        todaysDate = String.valueOf(year) + "-" + String.valueOf(month) + "-" + String.valueOf(date);
//        System.out.println("yeehaaw: "+todaysDate);

        int i=0;
        
        rsClass = dbObject.getDbTaskFromThisDate(todaysDate);
        
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
//        jPanel1.setBackground(java.awt.Color.WHITE);
        
       try {
           
            while(rsClass.next()){
                
//                System.out.println("well: " + rsClass.getString(3));
                cb = new JCheckBox();
                cb.setText(rsClass.getString("class_id"));
                cb.setFont(new Font("Serif", Font.PLAIN, 14));
                cb.setForeground(Color.BLACK);
                                
                String temp_taskId = rsClass.getString("task_id");
                cb.addActionListener(
                new ActionListener()
                {
//                       public void actionPerformed(ActionEvent event)
//                       {
//                           JOptionPane.showMessageDialog(null, event.getActionCommand());
//                        }
                    public void actionPerformed(ActionEvent event)
                       {
                           try {
                            Thread.sleep(2);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(TaskFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                           
                           
                           dbObject.taskComplete(Integer.parseInt(temp_taskId));
                           setCheckBox();
                       }
                }
                );
                
                jPanel1.add(cb);
                
                
                jlab = new JLabel();
                jlab.setText("  " + rsClass.getString("task_name"));
                jlab.setFont(new Font("Serif", Font.BOLD, 14));
                jlab.setForeground(Color.BLACK);
                jPanel1.add(jlab);
//                
//                String temp = rsClass.getString("class_id");
//                ResultSet rs2 = dbObject.getDbClass(temp);
                jlab = new JLabel();
//                jlab.setText(rs2.getString("class_name") + " - " + rsClass.getString("class_id"));
                jlab.setText("  " + rsClass.getString("due_date"));
                jlab.setFont(new Font("Serif", Font.BOLD, 14));
                jlab.setForeground(Color.BLACK);
                jPanel1.add(jlab);
                
                
                jlab = new JLabel();
                jlab.setText("  " + rsClass.getString("task_type"));
                jlab.setFont(new Font("Serif", Font.PLAIN, 14));
                jlab.setForeground(Color.BLACK);
                jPanel1.add(jlab);
                
                
                jlab = new JLabel();
                jlab.setText("  " +rsClass.getString("description"));
                jlab.setFont(new Font("Serif", Font.PLAIN, 12));
                jlab.setForeground(Color.BLACK);
                jPanel1.add(jlab);
                
//                jPanel1.add(Box.createVerticalGlue());
                jPanel1.add(Box.createVerticalStrut(20));
                
            }
            
            jScrollPane.setViewportView(jPanel1);
        } 
        catch (SQLException ex) {
            Logger.getLogger(TaskFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
//        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
//        jPanel1.setBackground(java.awt.Color.WHITE);
//        jScrollPane.setViewportView(jPanel1);
    }
    
     public void reset()
    {
        jPanel1 = new JPanel();
        jScrollPane.setViewportView(jPanel1);
    }
    
    
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("helloooooooooooooooooooooooooo");
                DatabaseClass dbClass = new DatabaseClass();
//                dbClass.setConnection();
                System.out.println("hellooooo agaaaaaaaaaaaaaaiiiiin");
//                Connection con = null;
//                try{
//                    Class.forName("com.mysql.jdbc.Driver");
//                    String db_url = "jdbc:mysql://localhost/studylifedb";
//                    con = DriverManager.getConnection(db_url, "root", "");
//                    Statement st = con.createStatement();
//                    String query = "Select * from classtable";
//                    ResultSet rs = st.executeQuery(query);
//                    while(rs.next())
//                    {
//                        System.out.println(rs.getString(1) + "\t" + rs.getString(2) + "\t");
//                    }
//                }catch(Exception e){
//                    System.out.println("My Error: " + e);
//                }
                
                new MainWindow().setVisible(true);
                
               // MainWindow().content.setSize(764,467);
//               try{
//                   if(con != null)
//                       con.close();
//               }catch(Exception e)
//               {
//                   System.out.println("oh no: " + e);
//               }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JPanel base;
    private javax.swing.JButton calendar;
    private javax.swing.JButton classesButton;
    private javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu2;
    private javax.swing.JButton tasks;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
